version: 2.1

jobs:
  test:
    docker:
      - image: circleci/ruby:2.6.6-node-browsers
        environment:
          RAILS_ENV: test
          MYSQL_HOST: 127.0.0.1
      - image: circleci/mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
          MYSQL_ROOT_HOST: '%'
    working_directory: ~/niwaai

    steps:
      - checkout
      - run:
          name: docker-compose build
          command: docker-compose -f docker-compose.prod.yml build
      - run:
          name: docker-compose up
          command: docker-compose -f docker-compose.test.yml up -d
      - run:
          name: sleep for waiting launch db
          command: sleep 1
      - run:
          name: create db
          command: docker-compose -f docker-compose.test.yml run web rails db:create
workflows:
  version: 2.1
  workflows:
    jobs:
      - test
